antispam_outbound_policies:
  - name: "Outbound Spam Action"
    description: "Action to take when outbound spam is detected"
    policy_type: "outbound"
    setting: "ActionWhenThresholdReached"
    expected_value: "BlockUser"

  - name: "External Message Limit per Hour"
    description: "Maximum number of external messages per hour"
    policy_type: "outbound"
    setting: "RecipientLimitExternalPerHour"
    expected_value: 400

  - name: "Internal Message Limit per Hour"
    description: "Maximum number of internal messages per hour"
    policy_type: "outbound"
    setting: "RecipientLimitInternalPerHour"
    expected_value: 800

  - name: "Daily Message Limit"
    description: "Maximum number of messages a user can send per day"
    policy_type: "outbound"
    setting: "RecipientLimitPerDay"
    expected_value: 800

  - name: "Enable Outbound Spam Notifications"
    description: "Send notifications when outbound spam is detected"
    policy_type: "outbound"
    setting: "NotifyOutboundSpam"
    expected_value: true

  - name: "Auto Forwarding Policy"
    description: "Control automatic forwarding to external domains"
    policy_type: "outbound"
    setting: "AutoForwardingMode"
    expected_value: "Automatic"

  - name: "BCC Suspicious Outbound Mail"
    description: "BCC suspicious outbound messages for monitoring"
    policy_type: "outbound"
    setting: "BccSuspiciousOutboundMail"
    expected_value: true

  - name: "Policy Enabled Status"
    description: "Ensure the outbound spam policy is enabled"
    policy_type: "outbound"
    setting: "Enabled"
    expected_value: true

  - name: "Outbound Spam Recipients Configured"
    description: "Ensure notification recipients are configured for outbound spam"
    policy_type: "outbound"
    setting: "NotifyOutboundSpamRecipients"
    expected_value: "not_null"

  - name: "BCC Additional Recipients Configured"
    description: "Ensure BCC recipients are configured for suspicious outbound mail"
    policy_type: "outbound"
    setting: "BccSuspiciousOutboundAdditionalRecipients"
    expected_value: "not_null"