# Defender for Office 365 Anti-Malware Policy Requirements
# Configuration-focused checks only (not tenant-specific values)

antimalware_policies:
  - name: "File Filter Enabled"
    setting: "EnableFileFilter"
    expected_value: true
    description: "Ensure file filtering is enabled to block dangerous file types"
    
  - name: "File Type Action - Quarantine"
    setting: "FileTypeAction"
    expected_value: "Quarantine"
    description: "Ensure dangerous file types are quarantined rather than blocked or delivered"
    
  - name: "Comprehensive File Types Blocked"
    setting: "FileTypes"
    expected_value: ["ace","apk","app","appx","ani","arj","bat","cab","cmd","com","deb","dex","dll","docm","elf","exe","hta","img","iso","jar","jnlp","kext","lha","lib","library","lnk","lzh","macho","msc","msi","msix","msp","mst","pif","ppa","ppam","reg","rev","scf","scr","sct","sys","uif","vb","vbe","vbs","vxd","wsc","wsf","wsh","xll","xz","z","ps1","rdp","Hta","js","rtf"]
    description: "Ensure comprehensive list of dangerous file types are blocked"
    
  - name: "ZAP Enabled"
    setting: "ZapEnabled"
    expected_value: true
    description: "Ensure Zero-hour Auto Purge is enabled for retroactive threat removal"
    
  - name: "Custom Notifications Disabled"
    setting: "CustomNotifications"
    expected_value: false
    description: "Ensure custom notifications are disabled to maintain security posture"
    
  - name: "External Sender Admin Notifications Disabled"
    setting: "EnableExternalSenderAdminNotifications"
    expected_value: false
    description: "Ensure external sender admin notifications are disabled"
    
  - name: "Internal Sender Admin Notifications Disabled"
    setting: "EnableInternalSenderAdminNotifications"
    expected_value: false
    description: "Ensure internal sender admin notifications are disabled"
    
  - name: "Quarantine Tag Set"
    setting: "QuarantineTag"
    expected_value: "AdminOnlyAccessPolicy"
    description: "Ensure quarantine tag is set to admin-only access for security"
