# Defender for Office 365 ATP Policy Requirements (Safe Docs)
# Configuration-focused checks only (not tenant-specific values)

atppolicy_policies:
  - name: "ATP for SharePoint, OneDrive, and Teams Enabled"
    setting: "EnableATPForSPOTeamsODB"
    expected_value: true
    description: "Ensure Advanced Threat Protection is enabled for SharePoint Online, OneDrive, and Microsoft Teams"
    
  - name: "Safe Documents Enabled"
    setting: "EnableSafeDocs"
    expected_value: true
    description: "Ensure Safe Documents protection is enabled for Office applications"
    
  - name: "Safe Documents Open Restricted"
    setting: "AllowSafeDocsOpen"
    expected_value: false
    description: "Ensure users cannot open documents that Safe Documents cannot verify as safe"
