# Exchange Online General Configuration Requirements
# Configuration-focused checks for various Exchange Online settings

# ATP Policy for O365 (Safe Docs) configuration
atppolicy_policies:
  - name: "ATP for SharePoint, OneDrive, and Teams Enabled"
    setting: "EnableATPForSPOTeamsODB"
    expected_value: true
    description: "Ensure Advanced Threat Protection is enabled for SharePoint Online, OneDrive, and Microsoft Teams"
    
  - name: "Safe Documents Enabled"
    setting: "EnableSafeDocs"
    expected_value: true
    description: "Ensure Safe Documents protection is enabled for Office applications"
    
  - name: "Safe Documents Open Restricted"
    setting: "AllowSafeDocsOpen"
    expected_value: false
    description: "Ensure users cannot open documents that Safe Documents cannot verify as safe"

# External Sender Notification In Outlook configuration
externalinoutlook_policies:
  - name: "External In Outlook Enabled"
    setting: "Enabled"
    expected_value: true
    description: "Ensure External In Outlook notifications are enabled to warn users about external emails"
    
  - name: "External In Outlook Identity Configured"
    setting: "Identity"
    expected_value: "not_null"
    description: "Verify External In Outlook configuration identity is properly set"

# Organization Configuration - Mail Auditing
organizationconfig_policies:
  - name: "Mail Auditing Enabled"
    setting: "AuditDisabled"
    expected_value: false
    description: "Ensure mail auditing is enabled by default (AuditDisabled should be false)"
    
  - name: "Direct Send Rejected"
    setting: "RejectDirectSend"
    expected_value: true
    description: "Ensure direct send is rejected to prevent unauthorized email relay"

# Report Submission Policy Configuration
reportsubmissionpolicy_policies:
  - name: "User Submission Options Enabled"
    setting: "DisableUserSubmissionOptions"
    expected_value: false
    description: "Ensure users can submit reports (DisableUserSubmissionOptions should be false)"
    
  - name: "Report to Microsoft Enabled"
    setting: "EnableReportToMicrosoft"
    expected_value: true
    description: "Ensure reporting to Microsoft is enabled for threat analysis"
    
  - name: "Junk Reporting to Custom Address"
    setting: "ReportJunkToCustomizedAddress"
    expected_value: true
    description: "Ensure junk email can be reported to customized address"
    
  - name: "Phishing Reporting to Custom Address"
    setting: "ReportPhishToCustomizedAddress"
    expected_value: true
    description: "Ensure phishing emails can be reported to customized address"
    
  - name: "Chat Message Reporting Enabled"
    setting: "ReportChatMessageEnabled"
    expected_value: true
    description: "Ensure users can report suspicious chat messages"
    
  - name: "Pre-Submit Message Enabled"
    setting: "PreSubmitMessageEnabled"
    expected_value: true
    description: "Ensure pre-submit messages are shown to users"
    
  - name: "Post-Submit Message Enabled"
    setting: "PostSubmitMessageEnabled"
    expected_value: true
    description: "Ensure post-submit messages are shown to users"
    
  - name: "Confirmation Notification Enabled"
    setting: "ConfirmationNotificationEnabled"
    expected_value: true
    description: "Ensure confirmation notifications are enabled for user submissions"

# DKIM (DomainKeys Identified Mail) signing configuration requirements
dkim_policies:
  - name: "DKIM Key Size Requirements"
    setting: "KeySize"
    expected_value: 2048
    description: "Both DKIM selector keys must be at least 2048 bits for security"
    
  - name: "DKIM Selector 1 Key Size"
    setting: "Selector1KeySize"
    expected_value: 2048
    description: "DKIM Selector 1 key must be at least 2048 bits"
    
  - name: "DKIM Selector 2 Key Size"
    setting: "Selector2KeySize"
    expected_value: 2048
    description: "DKIM Selector 2 key must be at least 2048 bits"
    
  - name: "DKIM Enabled Status"
    setting: "Enabled"
    expected_value: true
    description: "DKIM signing should be enabled for all domains"
