requirements:
  - name: "Block execution of potentially obfuscated scripts"
    check_id: "ASR_001"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutionofpotentiallyobfuscatedscripts"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutionofpotentiallyobfuscatedscripts_block"
    
  - name: "Block Win32 API calls from Office macros"
    check_id: "ASR_002"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockwin32apicallsfromofficemacros"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockwin32apicallsfromofficemacros_block"
    
  - name: "Block executable files from running unless they meet prevalence, age, or trusted list criterion"
    check_id: "ASR_003"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutablefilesrunningunlesstheymeetprevalenceagetrustedlistcriterion"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutablefilesrunningunlesstheymeetprevalenceagetrustedlistcriterion_block"
    
  - name: "Block Office communication applications from creating child processes"
    check_id: "ASR_004"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficecommunicationappfromcreatingchildprocesses"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficecommunicationappfromcreatingchildprocesses_block"
    
  - name: "Block all Office applications from creating child processes"
    check_id: "ASR_005"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockallofficeapplicationsfromcreatingchildprocesses"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockallofficeapplicationsfromcreatingchildprocesses_block"
    
  - name: "Block Adobe Reader from creating child processes"
    check_id: "ASR_006"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockadobereaderfromcreatingchildprocesses"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockadobereaderfromcreatingchildprocesses_block"
    
  - name: "Block credential stealing from the Windows local security authority subsystem (lsass.exe)"
    check_id: "ASR_007"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockcredentialstealingfromwindowslocalsecurityauthoritysubsystem"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockcredentialstealingfromwindowslocalsecurityauthoritysubsystem_block"
    
  - name: "Block JavaScript or VBScript from launching downloaded executable content"
    check_id: "ASR_008"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockjavascriptorvbscriptfromlaunchingdownloadedexecutablecontent"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockjavascriptorvbscriptfromlaunchingdownloadedexecutablecontent_block"
    
  - name: "Block webshell creation for servers"
    check_id: "ASR_009"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockwebshellcreationforservers"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockwebshellcreationforservers_block"
    
  - name: "Block untrusted and unsigned processes that run from USB"
    check_id: "ASR_010"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockuntrustedunsignedprocessesthatrunfromusb"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockuntrustedunsignedprocessesthatrunfromusb_block"
    
  - name: "Block persistence through WMI event subscription"
    check_id: "ASR_011"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockpersistencethroughwmieventsubscription"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockpersistencethroughwmieventsubscription_block"
    
  - name: "Block use of copied or impersonated system tools"
    check_id: "ASR_012"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockuseofcopiedorimpersonatedsystemtools"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockuseofcopiedorimpersonatedsystemtools_block"
    
  - name: "Block abuse of exploited vulnerable signed drivers"
    check_id: "ASR_013"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockabuseofexploitedvulnerablesigneddrivers"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockabuseofexploitedvulnerablesigneddrivers_block"
    
  - name: "Block process creations originating from PSExec and WMI commands"
    check_id: "ASR_014"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockprocesscreationsfrompsexecandwmicommands"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockprocesscreationsfrompsexecandwmicommands_block"
    
  - name: "Block Office applications from creating executable content"
    check_id: "ASR_015"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficeapplicationsfromcreatingexecutablecontent"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficeapplicationsfromcreatingexecutablecontent_block"
    
  - name: "Block Office applications from injecting code into other processes"
    check_id: "ASR_016"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficeapplicationsfrominjectingcodeintootherprocesses"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockofficeapplicationsfrominjectingcodeintootherprocesses_block"
    
  - name: "Block rebooting machine in Safe Mode"
    check_id: "ASR_017"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockrebootingmachineinsafemode"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockrebootingmachineinsafemode_block"
    
  - name: "Use advanced protection against ransomware"
    check_id: "ASR_018"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_useadvancedprotectionagainstransomware"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_useadvancedprotectionagainstransomware_block"
    
  - name: "Block executable content from email client and webmail"
    check_id: "ASR_019"
    setting_definition_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules"
    asr_rule_id: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutablecontentfromemailclientandwebmail"
    expected_value: "device_vendor_msft_policy_config_defender_attacksurfacereductionrules_blockexecutablecontentfromemailclientandwebmail_block"
    
  - name: "Enable controlled folder access"
    check_id: "ASR_020"
    setting_definition_id: "device_vendor_msft_policy_config_defender_enablecontrolledfolderaccess"
    expected_value: "device_vendor_msft_policy_config_defender_enablecontrolledfolderaccess_2"
